baseURL = "https://oystholl.github.io/hugohomepage/"
languageCode = "en-us"
title = "ResInsight"
theme = "learn"

[params]
disableSearch = false
disableHomeIcon = true
ordersectionsby = "weight"
disableShortcutsTitle = true


[[menu.shortcuts]]
	name = "Download"
	identifier = "download"
	url = "/project/download"
	weight = 20

[[menu.shortcuts]]
	name = "About"
	identifier = "about"
	url = "/project/about"
	weight = 10

