baseURL = "https://opm.github.io/ResInsight-UserDocumentation/"
#baseURL = "https://resinsight.org/"

languageCode = "en-us"
title = "ResInsight"
theme = "learn"
googleAnalytics = "UA-79509181-1"

[params]
disableSearch = false
disableHomeIcon = true
ordersectionsby = "weight"
disableShortcutsTitle = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[[menu.shortcuts]]
	name = "<i class='fas fa-info-circle'></i> About"
	identifier = "about"
	url = "/about"
	weight = 10

[[menu.shortcuts]]
	name = "<i class='fas fa-download'></i> Download and Install"
	identifier = "download"
	url = "/getting-started/download-and-install"
	weight = 20

[[menu.shortcuts]]
	name = "<i class='far fa-question-circle'></i> Support"
	identifier = "support"
	url = "/support"
	weight = 20
